### ISSUE TITLE
Remove composer.lock file

### ISSUE THREAD

**Issue by jaytaph** [jaytaph/RateLimitBundle#101]
@mcfedr  @KDederichs  I see that we have a composer.lock file in our repository. I think this is not suggested for libraries?

**Comment by goetas** [comment]
Agree, should be dropped

**Comment by KDederichs** [comment]
Yeah locking it is probably gonna cause trouble for some people so we should just drop it.

**Comment by mhor** [comment]
Issue can be closed, compose.lock was removed by [this commit](https://github.com/jaytaph/RateLimitBundle/commit/4542709b1da95e1a67da0b9ee938bd24e8a074b9)
