### ISSUE TITLE
Symfony cache support?

### ISSUE THREAD

**Issue by irmantas** [jaytaph/RateLimitBundle#103]
Hi,

Just tried to install this bundle on new Symfony 5 project and got following error.

```
The service "noxlogic_rate_limit.rate_limit_annotation_listener" has a dependency on a non-existent service "snc_redis.default_client".
```
Thing is I'm using Symfony cache component and to install other cache abstraction packages (most of them are unsupported or deprecated) is not so convenient way to do.
Adding Symfony cache as dependency it would solve most of the problems.

**Comment by Snowbaha** [comment]
Hello,

Here is an answer [there](https://github.com/jaytaph/RateLimitBundle/issues/77#issuecomment-516897849).

**Comment by fracz** [comment]
My example with symfony cache is:

```
noxlogic_rate_limit:
  storage_engine: simple_cache
  simple_cache_service: thecache
```

And then, define a cache service that uses the symfony cache or even the symfony cache class directly:

```
thecache:
  class: Symfony\Component\Cache\Simple\FilesystemCache
```

**Comment by drzraf** [comment]
To complete this, don't forget to require `psr/simple-cache` because neither `noxlogic/ratelimit-bundle` neither newer version of `symfony/cache` would.

**Comment by axi** [comment]
And with PSR cache

```
noxlogic_rate_limit:
  storage_engine: cache
  cache_service: psrcacheservice
```
with 
```
services:
  psrcacheservice:
    class: Symfony\Component\Cache\Adapter\ApcuAdapter
```

**Comment by drzraf** [comment]
Now `Symfony\Component\Cache\Adapter\FilesystemAdapter` with Symfony 5.x (but cache key generation is different, thus not compatible with existing cache-entries)

**Comment by goetas** [comment]
This bundle provides the `\Noxlogic\RateLimitBundle\Service\Storage\PsrCache` class, that takes a `\Symfony\Component\Cache\Adapter\Psr16Adapter` implementation. That meas that any symfony cache  impl can be used with this bundle.
