### ISSUE TITLE
update dependency sensio/framework-extra-bundle 6.*

### ISSUE THREAD

**Issue by axi** [jaytaph/RateLimitBundle#117]
sensio/framework-extra-bundle has been updated to 6.*, we can't update as long as dependency restriction is not fixed.

in composer.json
```
    "require": {
        "php": "^7.2",
        "symfony/framework-bundle": "^3.4|^4.3|^5.0",
        "sensio/framework-extra-bundle": "^3.0|^4.0|^5.0"
    },
```
should be
```
    "require": {
        "php": "^7.2",
        "symfony/framework-bundle": "^3.4|^4.3|^5.0",
        "sensio/framework-extra-bundle": "^3.0|^4.0|^5.0|^6.0"
    },
```

thanks

**Comment by axi** [comment]
I haven't tested out but changelog doesn't talk about BC
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/CHANGELOG.md

**Comment by jaytaph** [comment]
I think we can setup a new minor release for this

**Comment by jaytaph** [comment]
Created 1.16.1 with the new dependency. Let me know if you have any issues.
