### ISSUE TITLE
Allow wildcard in path for path_limit

### ISSUE THREAD

**Issue by asilelik** [jaytaph/RateLimitBundle#119]
Currently, only method wildcard works [[here](https://github.com/jaytaph/RateLimitBundle/blob/cb7b1fd480d180023a7dc57c7809e0b9daf4d9ed/Util/PathLimitProcessor.php#L70)]. As a feature request, we can add the functionality for allowing wildcard in path matches. 

Example use-case: Rate limit all POST requests

If my request is valid, I can create the PR for it.

**Comment by jaytaph** [comment]
Sounds like a good idea. If you have a PR, we're happy to look into it and merge it

**Comment by asilelik** [comment]
Thank you for your reply. I've created the PR.
