### ISSUE TITLE
sensio/framework-extra-bundle is deprecated

### ISSUE THREAD

**Issue by goetas** [jaytaph/RateLimitBundle#130]
`sensio/framework-extra-bundle` is deprecated, however this bundle uses it to handle the `@RateLimit` annotation.

Are you ok if I send a pull request in which:
- drop the  `@RateLimit` annotation in favor of a PHP attribute?
- drop php 7 support
- drop symfony 3.x and 4.x support?

if this is merged will require a major release

(i'm also offering my help to maintain this bundle)

**Comment by jaytaph** [comment]
Hi. Yes, i would love a PR for this. I don't have much time myself so if you like I can add you as a maintainer

**Comment by axi** [comment]
I started working on that, I should be able to offer a PR soon

**Comment by axi** [comment]
@jaytaph could you have a look on #132 PR ?

**Comment by goetas** [comment]
@jaytaph  I see that @axi  did an excellent work with #132 (he was faster than me to provide a PR). I did a review and seems very good!

I still offer my help in maintaining some bundle.

**Comment by goetas** [comment]
I'm starting to think that if there will be a 2.x release, maybe makes sense to drop `OAuthServerBundle` support too?

**Comment by jaytaph** [comment]
> I still offer my help in maintaining this bundle (limited time but i expect that in the next months should get better).
help is welcome. I'm not really in the position to maintain it much myself to be honest. I've added you already as a collaborator.

**Comment by goetas** [comment]
@jaytaph thanks, I was trying to do some maintenance but I was not getting enabled the button to merge pull requests, only now I realize that is because of the code rewiew rules. 
Could you please relax the code rewiew rules on this repo so I can merge code without those approvals. Those rules are very useful but this repo has very little activity that makes it hard to get the needed approvals.

**Comment by jaytaph** [comment]
:meeseeks: sure can do!
