### ISSUE TITLE
Split the rate limit bundle into a rate limit library

### ISSUE THREAD

**Issue by jaytaph** [jaytaph/RateLimitBundle#21]
This would allow us to use the rate limiter in other frameworks as well..

**Comment by sagikazarmark** [comment]
:+1: 

Would be a great opportunity to implement PSR6 #25

**Comment by sagikazarmark** [comment]
Another idea: create a generic throttle library which can handle any kind of throttles (like maximum failed login attempts/30 minutes, etc)

**Comment by alister** [comment]
It may also help with a project I'll likely be working on - using the [Redis-Cell](https://redislabs.com/blog/redis-cell-rate-limiting-redis-module/) module that performs near-native rate limiting within Redis, as a storage engine for this bundle.

**Comment by goetas** [comment]
Symfony ships already a rate limiter component, I think that a dedicated lib will bring little benefit here https://symfony.com/doc/current/rate_limiter.html
