### ISSUE TITLE
Support PSR-6 Cache engines

### ISSUE THREAD

**Issue by sagikazarmark** [jaytaph/RateLimitBundle#25]
PSR6 is just being accepted (at least the vote is happening now). Would be nice to be able to use PSR6 compliant cache engines with this bundle.

**Comment by jaytaph** [comment]
Great idea! I think we can set something up quite easily..

**Comment by mcfedr** [comment]
I've just added support for PSR-16 Simple caches in version 1.9, but a PR for PSR-6 caches would be great
