### ISSUE TITLE
Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Template::setOwner() must be of the type array, object given

### ISSUE THREAD

**Issue by NadaBen** [jaytaph/RateLimitBundle#34]
Hello,
How can i know how many calls are still available for each user ? 
because for me , when a client exseeds the rate, this error is shown;

```
{
  "code": 500,
  "message": "Catchable Fatal Error: Argument 1 passed to Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Template::setOwner() must be of the type array, object given, called in C:\\wamp\\www\\VCycle_API\\app\\cache\\dev\\classes.php on line 7678 and defined"
}
```

for me i want to give 429 TOO MANY REQUESTS error as result in this case

**Comment by jaytaph** [comment]
Thanks for the bug report.

It seems that this was an issue solved by #42.
