### ISSUE TITLE
Include Retry-After header in response

### ISSUE THREAD

**Issue by eduardoweiland** [jaytaph/RateLimitBundle#35]
The [RFC 6585](https://tools.ietf.org/html/rfc6585#section-4) states that the HTTP 429 status response MAY include the Retry-After header to inform the client how much time it needs to wait before making another request.

Maybe there could be an option in the bundle configuration to add or not this header in the response sent to the client when it reaches the specified limit.

**Comment by symfonyUser** [comment]
Currently, Bundle Provides reset time in form of  _X-RateLimit-Reset_ header , from which wait time could be deduced
