### ISSUE TITLE
could not set path_limits

### ISSUE THREAD

**Issue by dre0** [jaytaph/RateLimitBundle#36]
after setting path,following error is  thrown

>  Invalid type for path "noxlogic_rate_limit.path_limits.path". Expected array, but got string

```
noxlogic_rate_limit:
    enabled:    true
    storage_engine: "redis"
    redis_client:   default
    rate_response_code: 429
    rate_response_exception:    Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException
    rate_response_message:  'You exceeded the rate limit'
    display_headers:    true
    headers:
        limit:  X-RateLimit-Limit
        remaining:  X-RateLimit-Remaining
        reset:  X-RateLimit-Reset
    # Rate limits for paths
    path_limits:
        path:   /api
        methods:
            # Default:
            - *
        limit:  10
        period: 60
```

Could anyone provide correct example for path_limits configuration 
like for /api route and 10 limit for 60 seconds

**Comment by Nightbr** [comment]
If you look at the code:

```
    # Rate limits for paths
    path_limits:
        -   path: '^/api'
            limit: 100
            period: 10
```

But it doesn't work because I don't see in the code where is the call to the `PathLimitProcessor` service to handle this config...

Any help from maintainer please ?

**Comment by carl-boisvert** [comment]
Yeah, I can't seem to make it work either.

**Comment by luliandro** [comment]
it works if you use a specific path (ie: '/users') not for regex

**Comment by dre0** [comment]
can provide example

**Comment by luliandro** [comment]
`noxlogic_rate_limit:
      enabled:              true
      path_limits:
        - path: '/users'
          limit: 100
          period: 3600
`

This will limit to 100 request/hour on the path /users
