### ISSUE TITLE
Redis Reset ERR wrong number of arguments for 'hdel' command

### ISSUE THREAD

**Issue by moonraking** [jaytaph/RateLimitBundle#39]
Service/Storage/Redis.php::resetRate($myKey) is throwing an error:

> ERR wrong number of arguments for 'hdel' command

I believe the problem is that the hdel command is for removing a field from the hash and not the whole key.

I think we should be calling the del command to remove the whole hash.

**Comment by jaytaph** [comment]
It seems that `hdel` isn't using any fields but only the key name. It should be called with the fields we need to delete from that key: `$this->client->hdel($key, 'limit', 'calls', 'reset');` would most likely do the trick.

**Comment by mcfedr** [comment]
Now using `del` so this should be fixed
