### ISSUE TITLE
Adding a Service that can be used anywhere in the code?

### ISSUE THREAD

**Issue by wodka** [jaytaph/RateLimitBundle#41]
Basically something like:

```php
$key = 'my_own_fancy_key';
$limit = 1;
$period = 60;

if ($this->get('limiter')->withinLimits($key, $limit, $period)) {
  // fancy we can :)
}
```

do you want a pull request for this?

**Comment by jaytaph** [comment]
I think it's possible to get this information directly from the service without too much trouble and without and BC breaks, so I'm always happy to accept PR's for this.
