### ISSUE TITLE
Conflict with FrameworkExtraBundle

### ISSUE THREAD

**Issue by NadaBen** [jaytaph/RateLimitBundle#42]
Hello,
I have a problem, when it exceeds the rate limit, 
I have this error

> message": "Catchable Fatal Error: Argument 1 passed to Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Template::setOwner() must be of the type array, object given
do you have an idea how to fixe that ?

**Comment by laurent35240** [comment]
Hi,
We had the same problem
We wrote this PR for fixint it: https://github.com/jaytaph/RateLimitBundle/pull/44

**Comment by jaytaph** [comment]
I've merged the PR for the new release. Thanks for the bug report!
