### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by goetas** [jaytaph/RateLimitBundle#49]
Just wanted to say **Thank you**.

Installed the bundle, configured it and installed redis, inserted the annotation on a rest endpoint...

Done! Just works!

Time spent: 15 minutes (mostly waiting stuff to be downloaded)

:tada: :tada: :tada:

**Comment by jaytaph** [comment]
Thank you for using the bundle. If you find any issues, you are always free to open an issue or send a pull request.
