### ISSUE TITLE
I still have Lsw\MemcacheBundle\DataCollector\MemcacheDataCollector::addClient() must be an instance of Lsw\MemcacheBundle\Cache\LoggingMemcacheInterface, instance of Lsw\MemcacheBundle\Cache\AntiDogPileMemcache given

### ISSUE THREAD

**Issue by speeeeeed2006** [jaytaph/RateLimitBundle#50]
Hello, 

I have try to use this bundle and add it to my project but I can't use it with memcach because I have the same error I seen in another issue 
Lsw\MemcacheBundle\DataCollector\MemcacheDataCollector::addClient() must be an instance of Lsw\MemcacheBundle\Cache\LoggingMemcacheInterface, instance of Lsw\MemcacheBundle\Cache\AntiDogPileMemcache given
the problem is the only solution given is to change to cacheDoctrine which it use APC and I didn't want to use it and Redis is a paying solution. 
Someone have maybe a fix or a way to correct this? 
Maybe an alternative?

**Comment by mcfedr** [comment]
If there is a `\Memcached` instance in your container, you can set it in conf as `memcache_service: "service_name"`
