### ISSUE TITLE
Notice: Undefined index: limit

### ISSUE THREAD

**Issue by muzzzko** [jaytaph/RateLimitBundle#59]
Hi, I have an error in RateLimitBundle/Service/Storage/Redis.php. When a new Rate is created, the time of its destruction is established.
![2017-11-29 12 04 55](https://user-images.githubusercontent.com/25665029/33362303-a980458e-d4fd-11e7-8869-10a805af6e90.png)

when a new request is made, the presence of this key in Redis is checked,

![2017-11-29 12 06 34](https://user-images.githubusercontent.com/25665029/33362323-cc6c9750-d4fd-11e7-9b94-145e67af1792.png)

and is called GetRateInfo, but at that point the key can be deleted, because the expire function was called earlier.

![2017-11-29 12 07 11](https://user-images.githubusercontent.com/25665029/33362347-e42de5ce-d4fd-11e7-9a8f-e4f417bd5d11.png)

So there is an error Notice: Undefined index: limit. 

Thanks!

**Comment by mcfedr** [comment]
Fixed in 1.8
