### ISSUE TITLE
Add Note to Readme that IP-Based rate-limiting is not the default

### ISSUE THREAD

**Issue by IljaN** [jaytaph/RateLimitBundle#83]
I assumed that this bundle does ip-based rate-limiting out of the box. To get this functionality a custom key-generator has to be written.

**Comment by IljaN** [comment]
I could provide a PR which allows to configure this out of the box.

**Comment by mcfedr** [comment]
I think that would be interesting.

**Comment by goetas** [comment]
This bit me too! Should be documented!

**Comment by mcfedr** [comment]
I think a PR for this would be great, would probably need to be a config option to enable it by default as would have BC issues

**Comment by goetas** [comment]
> I think a PR for this would be great, would probably need to be a config option to enable it by default as would have BC issues

I personally disagree with the idea of having IP limiting by default. this bundle should not make this kind of decisions (as example our API has 90% or rate limitations not based on user's IP).

If we document it properly, i do not see a need to have  IP limiting by default.

**Comment by mcfedr** [comment]
If there is a bundled ip based rate limiter, that you have to enable, i think that makes it simple to get started, and also serves as a good example of how to use the bundle, although I agree, for most uses, you will want to build something more custom, but there would be no pressure to use the built in limiter

**Comment by goetas** [comment]
i will provide a doc pr in the next 10-20 min

**Comment by goetas** [comment]
here it is https://github.com/jaytaph/RateLimitBundle/pull/84
