### ISSUE TITLE
noxlogic/ratelimit-bundle is not up to date

### ISSUE THREAD

**Issue by goetas** [jaytaph/RateLimitBundle#85]
The 1.14.0 tag is not available on packagist.

Is the webhook properly configured?

https://packagist.org/packages/noxlogic/ratelimit-bundle

**Comment by mcfedr** [comment]
Unfortunately I don't have access to these settings only @jaytaph can fix this.

**Comment by jaytaph** [comment]
Just saw this message.. I'll check and fix this.

**Comment by jaytaph** [comment]
I've fixed the legacy webhook now. New releases should now automatically be pushed to packagist.
