### ISSUE TITLE
Support new `EventDispatcherInterface`

### ISSUE THREAD

**Issue by michelezamuner** [jaytaph/RateLimitBundle#91]
From version 4.3.0, `EventDispatcherInterface` has changed: now the `dispatch()` method, instead of taking an event name as first parameter, and an event object as second, takes only the event object itself. There is a fallback for applications using event names, consisting in passing an optional second parameter as event name, but it's marked as deprecated.

https://github.com/symfony/event-dispatcher/blob/v4.3.2/EventDispatcherInterface.php
https://github.com/symfony/event-dispatcher-contracts/blob/master/EventDispatcherInterface.php

**Comment by goetas** [comment]
There is a "work in progress" PR, https://github.com/jaytaph/RateLimitBundle/pull/90

Can you review it? Helping us to solve the issue

**Comment by jaytaph** [comment]
@goetas I think this is already been done in the latest release?

**Comment by goetas** [comment]
Yes, thank you!
