### ISSUE TITLE
FilterControllerEvent deprecated in Symfony 4.3

### ISSUE THREAD

**Issue by TheLoneUs** [jaytaph/RateLimitBundle#95]
FilterControllerEvent should be changed to ControllerEvent

In https://github.com/jaytaph/RateLimitBundle/blob/master/EventListener/RateLimitAnnotationListener.php

I checked the PRs and it isn't fixed in this PR yet: https://github.com/jaytaph/RateLimitBundle/pull/90/files

**Comment by goetas** [comment]
Since https://github.com/jaytaph/RateLimitBundle/pull/132 Symfony 4 and 5 are not supported anymore
